version: '3.9'

services:
  couchbase:
    image: couchbase:community
    hostname: couchbase
    container_name: couchbase
    ports:
      - '8091:8091' # Admin UI
      - '8092:8092' # Query UI
      - '8093:8093' # Query service
      - '8094:8094' # Search service
      - '11210:11210' # Data service
    environment:
      - COUCHBASE_ADMIN_USERNAME=admin # Admin username
      - COUCHBASE_ADMIN_PASSWORD=password # Admin password
      - COUCHBASE_BUCKET=my_bucket # Default bucket name
      - COUCHBASE_BUCKET_RAMSIZE=256 # RAM quota for the bucket (in MB)
      - COUCHBASE_SERVICES=data,index,query,fts # Enable specific services
    volumes:
      - couchbase_data:/opt/couchbase/var
      - couchbase_config:/opt/couchbase/etc

volumes:
  couchbase_data:
  couchbase_config:
