services:
  hashicorp-vault:
    image: hashicorp/vault:latest
    hostname: hashicorp-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: '83df719b-2d56-4d2e-85cb-e11bb961a580'
    ports:
      - 8200:8200
    privileged: true
