services:
  sqlite:
    image: sqlite:latest
    hostname: sqlite
    container_name: sqlite
    volumes:
      - sqlite-data:/mydatabase
    ports:
      - '5432:5432'
    restart: always

volumes:
  sqlite-data:
