services:
  activemq:
    image: rmohr/activemq:5.15.9
    hostname: activemq
    container_name: activemq
    ports:
      - '61616:61616' # Main port for JMS
      - '8161:8161' # Web console
      - '5672:5672' # AMQP
      - '61613:61613' # STOMP
      - '1883:1883' # MQTT
      - '61614:61614' # OpenWire
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048
