services:
  rabbitmq:
    image: rabbitmq:4-management # Includes management UI
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    driver: local
